#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Jan 18, 2020 05:32:37 PM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 692x551+380+176
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4336 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Scheduling System"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but44 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Back 
    vTcl:DefineAlias "$top.but44" "back_btn" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe45
    vTcl:DefineAlias "$top.tSe45" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Room Name:} 
    vTcl:DefineAlias "$top.lab46" "roomName_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent47 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent47" "roomName_entry" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Grade: 
    vTcl:DefineAlias "$top.lab48" "grade_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent49 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent49" "grade_entry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but50 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 9} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Add 
    vTcl:DefineAlias "$top.but50" "add_btn" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr51 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$top.scr51" "grade_treeview" vTcl:WidgetProc "Toplevel1" 1
        .top42.scr51.01 configure -columns {Col1}
        .top42.scr51.01 heading #0 -text {Tree}
        .top42.scr51.01 heading #0 -anchor center
        .top42.scr51.01 column #0 -width 210
        .top42.scr51.01 column #0 -minwidth 20
        .top42.scr51.01 column #0 -stretch 1
        .top42.scr51.01 column #0 -anchor w
        .top42.scr51.01 heading Col1 -text {Col1}
        .top42.scr51.01 heading Col1 -anchor center
        .top42.scr51.01 column Col1 -width 211
        .top42.scr51.01 column Col1 -minwidth 20
        .top42.scr51.01 column Col1 -stretch 1
        .top42.scr51.01 column Col1 -anchor w
    button $top.but52 \
        -activebackground #1aff12 -activeforeground #000000 \
        -background #1aff12 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text {ADD ROOM} 
    vTcl:DefineAlias "$top.but52" "addRoom_btn" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che43 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Laboratory -variable che43 
    vTcl:DefineAlias "$top.che43" "lab_check" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but44 \
        -in $top -x 10 -y 10 -width 157 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSe45 \
        -in $top -x 0 -y 70 -width 1160 -anchor nw -bordermode inside 
    place $top.lab46 \
        -in $top -x 0 -relx 0.011 -y 90 -width 114 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 140 -y 90 -width 164 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.011 -y 140 -width 64 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent49 \
        -in $top -x 140 -y 140 -width 164 -height 40 -anchor nw \
        -bordermode ignore 
    place $top.but50 \
        -in $top -x 320 -y 0 -rely 0.265 -width 67 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.scr51 \
        -in $top -x 20 -y 210 -width 440 -relwidth 0 -height 247 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 20 -y 480 -width 197 -relwidth 0 -height 54 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.che43 \
        -in $top -x 319 -y 100 -width 116 -relwidth 0 -height 32 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

