#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Jan 17, 2020 12:48:19 PM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1207x536+244+218
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4336 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Scheduling System"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but43 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Back 
    vTcl:DefineAlias "$top.but43" "back_btn" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe44
    vTcl:DefineAlias "$top.tSe44" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Grade: 
    vTcl:DefineAlias "$top.lab45" "grade_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent46 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent46" "grade_entry" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Subject: 
    vTcl:DefineAlias "$top.lab47" "subject_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent48" "subject_entry" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Duration: 
    vTcl:DefineAlias "$top.lab49" "duration_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent50" "duration_entry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but51 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Add 
    vTcl:DefineAlias "$top.but51" "addSubject_btn" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr52 \
        -background $vTcl(actual_gui_bg) -height 247 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 440 
    vTcl:DefineAlias "$top.scr52" "subject_treeview" vTcl:WidgetProc "Toplevel1" 1
        .top42.scr52.01 configure -columns {Col1}
        .top42.scr52.01 heading #0 -text {Tree}
        .top42.scr52.01 heading #0 -anchor center
        .top42.scr52.01 column #0 -width 210
        .top42.scr52.01 column #0 -minwidth 20
        .top42.scr52.01 column #0 -stretch 1
        .top42.scr52.01 column #0 -anchor w
        .top42.scr52.01 heading Col1 -text {Col1}
        .top42.scr52.01 heading Col1 -anchor center
        .top42.scr52.01 column Col1 -width 211
        .top42.scr52.01 column Col1 -minwidth 20
        .top42.scr52.01 column Col1 -stretch 1
        .top42.scr52.01 column Col1 -anchor w
    button $top.but53 \
        -activebackground #1aff12 -activeforeground #000000 \
        -background #1aff12 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text SUBMIT 
    vTcl:DefineAlias "$top.but53" "submit_btn" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Time In:} 
    vTcl:DefineAlias "$top.lab43" "timeIn_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent44 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent44" "timeIn_entry" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Time Out:} 
    vTcl:DefineAlias "$top.lab46" "timeOut_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent47 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent47" "timeOut_entry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Add 
    vTcl:DefineAlias "$top.but48" "addBreaktime_btn" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr49 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$top.scr49" "breaktime_treeview" vTcl:WidgetProc "Toplevel1" 1
        .top42.scr49.01 configure -columns {Col1}
        .top42.scr49.01 heading #0 -text {Tree}
        .top42.scr49.01 heading #0 -anchor center
        .top42.scr49.01 column #0 -width 210
        .top42.scr49.01 column #0 -minwidth 20
        .top42.scr49.01 column #0 -stretch 1
        .top42.scr49.01 column #0 -anchor w
        .top42.scr49.01 heading Col1 -text {Col1}
        .top42.scr49.01 heading Col1 -anchor center
        .top42.scr49.01 column Col1 -width 211
        .top42.scr49.01 column Col1 -minwidth 20
        .top42.scr49.01 column Col1 -stretch 1
        .top42.scr49.01 column Col1 -anchor w
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but43 \
        -in $top -x 10 -y 10 -width 157 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tSe44 \
        -in $top -x 0 -y 70 -width 1210 -anchor nw -bordermode inside 
    place $top.lab45 \
        -in $top -x 10 -y 90 -width 64 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent46 \
        -in $top -x 90 -y 90 -width 164 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 10 -y 150 -width 64 -height 41 -anchor nw \
        -bordermode ignore 
    place $top.ent48 \
        -in $top -x 90 -y 150 -width 164 -height 40 -anchor nw \
        -bordermode ignore 
    place $top.lab49 \
        -in $top -x 260 -y 150 -width 84 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 350 -y 150 -width 164 -height 40 -anchor nw \
        -bordermode ignore 
    place $top.but51 \
        -in $top -x 520 -y 0 -rely 0.2901 -width 67 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.scr52 \
        -in $top -x 90 -y 210 -width 440 -relwidth 0 -height 247 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 950 -y 470 -width 187 -relwidth 0 -height 54 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 620 -y 150 -width 64 -height 41 -anchor nw \
        -bordermode ignore 
    place $top.ent44 \
        -in $top -x 700 -y 150 -width 164 -height 40 -anchor nw \
        -bordermode ignore 
    place $top.lab46 \
        -in $top -x 870 -y 150 -width 84 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 960 -y 150 -width 164 -height 40 -anchor nw \
        -bordermode ignore 
    place $top.but48 \
        -in $top -x 1130 -y 0 -rely 0.289 -width 67 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.scr49 \
        -in $top -x 700 -y 210 -width 440 -height 247 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

