#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Jan 13, 2020 11:19:05 AM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 1154x414+233+146
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4336 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Scheduling System"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::separator $top.tSe43
    vTcl:DefineAlias "$top.tSe43" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -text {First Name:} 
    vTcl:DefineAlias "$top.lab44" "firstName_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent45 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent45" "firstName_entry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Back 
    vTcl:DefineAlias "$top.but46" "back_btn" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Middle Name:} 
    vTcl:DefineAlias "$top.lab47" "middleName_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent48 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent48" "middleName_entry" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Last Name:} 
    vTcl:DefineAlias "$top.lab49" "lastName_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent50" "lastName_entry" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Total Hours:} 
    vTcl:DefineAlias "$top.lab51" "totalHours_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent52 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent52" "totalHours_entry" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Grade: 
    vTcl:DefineAlias "$top.lab53" "grade_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent55 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent55" "grade_entry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but56 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Add 
    vTcl:DefineAlias "$top.but56" "addGrade_btn" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr57 \
        -background $vTcl(actual_gui_bg) -height 197 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 350 
    vTcl:DefineAlias "$top.scr57" "grade_treeview" vTcl:WidgetProc "Toplevel1" 1
        .top42.scr57.01 configure -columns {Col1}
        .top42.scr57.01 heading #0 -text {Tree}
        .top42.scr57.01 heading #0 -anchor center
        .top42.scr57.01 column #0 -width 165
        .top42.scr57.01 column #0 -minwidth 20
        .top42.scr57.01 column #0 -stretch 1
        .top42.scr57.01 column #0 -anchor w
        .top42.scr57.01 heading Col1 -text {Col1}
        .top42.scr57.01 heading Col1 -anchor center
        .top42.scr57.01 column Col1 -width 166
        .top42.scr57.01 column Col1 -minwidth 20
        .top42.scr57.01 column Col1 -stretch 1
        .top42.scr57.01 column Col1 -anchor w
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Subject: 
    vTcl:DefineAlias "$top.lab58" "subject_lbl" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent59 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent59" "subject_entry" vTcl:WidgetProc "Toplevel1" 1
    button $top.but60 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Add 
    vTcl:DefineAlias "$top.but60" "addSubject_btn" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr61 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$top.scr61" "subject_treeview" vTcl:WidgetProc "Toplevel1" 1
        .top42.scr61.01 configure -columns {Col1}
        .top42.scr61.01 heading #0 -text {Tree}
        .top42.scr61.01 heading #0 -anchor center
        .top42.scr61.01 column #0 -width 165
        .top42.scr61.01 column #0 -minwidth 20
        .top42.scr61.01 column #0 -stretch 1
        .top42.scr61.01 column #0 -anchor w
        .top42.scr61.01 heading Col1 -text {Col1}
        .top42.scr61.01 heading Col1 -anchor center
        .top42.scr61.01 column Col1 -width 166
        .top42.scr61.01 column Col1 -minwidth 20
        .top42.scr61.01 column Col1 -stretch 1
        .top42.scr61.01 column Col1 -anchor w
    button $top.but62 \
        -activebackground #1aff12 -activeforeground #000000 \
        -background #1aff12 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text {ADD TEACHER} 
    vTcl:DefineAlias "$top.but62" "addTeacher_btn" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tSe43 \
        -in $top -x 0 -y 70 -width 0 -relwidth 1.008 -anchor nw \
        -bordermode inside 
    place $top.lab44 \
        -in $top -x 0 -y 90 -width 124 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent45 \
        -in $top -x 170 -y 90 -width 184 -relwidth 0 -height 40 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 10 -y 10 -width 157 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.01 -y 160 -width 124 -height 41 -anchor nw \
        -bordermode ignore 
    place $top.ent48 \
        -in $top -x 170 -y 160 -width 184 -height 40 -anchor nw \
        -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -y 230 -width 124 -height 41 -anchor nw \
        -bordermode ignore 
    place $top.ent50 \
        -in $top -x 170 -y 230 -width 184 -height 40 -anchor nw \
        -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.004 -y 300 -width 124 -height 41 -anchor nw \
        -bordermode ignore 
    place $top.ent52 \
        -in $top -x 170 -y 300 -width 184 -height 40 -anchor nw \
        -bordermode ignore 
    place $top.lab53 \
        -in $top -x 360 -y 90 -width 124 -height 41 -anchor nw \
        -bordermode ignore 
    place $top.ent55 \
        -in $top -x 470 -y 90 -width 184 -height 40 -anchor nw \
        -bordermode ignore 
    place $top.but56 \
        -in $top -x 670 -y 0 -rely 0.233 -width 67 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.scr57 \
        -in $top -x 390 -y 140 -width 350 -relwidth 0 -height 197 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 750 -y 90 -width 124 -height 41 -anchor nw \
        -bordermode ignore 
    place $top.ent59 \
        -in $top -x 860 -y 90 -width 184 -height 40 -anchor nw \
        -bordermode ignore 
    place $top.but60 \
        -in $top -x 1060 -y 0 -rely 0.232 -width 67 -height 34 -anchor nw \
        -bordermode ignore 
    place $top.scr61 \
        -in $top -x 780 -y 140 -width 350 -height 197 -anchor nw \
        -bordermode ignore 
    place $top.but62 \
        -in $top -x 940 -y 350 -width 187 -relwidth 0 -height 54 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

