#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Jan 13, 2020 05:23:34 PM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m51" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1200x651+199+125
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4336 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    button $top.but43 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text {Select File} 
    vTcl:DefineAlias "$top.but43" "selectFile_btn" vTcl:WidgetProc "Toplevel1" 1
    button $top.but44 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text {Add Teachers} 
    vTcl:DefineAlias "$top.but44" "addTeachers_btn" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text {Add Rooms} 
    vTcl:DefineAlias "$top.but45" "addRooms_btn" vTcl:WidgetProc "Toplevel1" 1
    button $top.but46 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text {Add Subjects} 
    vTcl:DefineAlias "$top.but46" "addSubjects_btn" vTcl:WidgetProc "Toplevel1" 1
    button $top.but47 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text {Add Breaktime} 
    vTcl:DefineAlias "$top.but47" "addBreaktime_btn" vTcl:WidgetProc "Toplevel1" 1
    button $top.but48 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text {Add School Year} 
    vTcl:DefineAlias "$top.but48" "addSchoolYear_btn" vTcl:WidgetProc "Toplevel1" 1
    button $top.but49 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text {Teacher's Schedule} 
    vTcl:DefineAlias "$top.but49" "teacherSchedule_btn" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $top.tSe50
    vTcl:DefineAlias "$top.tSe50" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m51
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Grade: 
    vTcl:DefineAlias "$top.lab52" "grade_lbl" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo54 \
        -font {-family {Segoe UI} -size 12} -textvariable combobox \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo54" "grade_box" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Section: 
    vTcl:DefineAlias "$top.lab55" "section_lbl" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo56 \
        -font {-family {Segoe UI} -size 12} -textvariable combobox \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo56" "section_box" vTcl:WidgetProc "Toplevel1" 1
    button $top.but57 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Search 
    vTcl:DefineAlias "$top.but57" "search_btn" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text SCHEDULE 
    vTcl:DefineAlias "$top.lab58" "schedule_lbl" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure Treeview.Heading -background $vTcl(pr,guicomplement_color)
    ttk::style configure Treeview.Heading -font "$vTcl(actual_gui_font_dft_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $top.scr59 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$top.scr59" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1
        .top42.scr59.01 configure -columns {Col1}
        .top42.scr59.01 heading #0 -text {Tree}
        .top42.scr59.01 heading #0 -anchor center
        .top42.scr59.01 column #0 -width 580
        .top42.scr59.01 column #0 -minwidth 20
        .top42.scr59.01 column #0 -stretch 1
        .top42.scr59.01 column #0 -anchor w
        .top42.scr59.01 heading Col1 -text {Col1}
        .top42.scr59.01 heading Col1 -anchor center
        .top42.scr59.01 column Col1 -width 581
        .top42.scr59.01 column Col1 -minwidth 20
        .top42.scr59.01 column Col1 -stretch 1
        .top42.scr59.01 column Col1 -anchor w
    label $top.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 14} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Active School Year:} 
    vTcl:DefineAlias "$top.lab43" "activeSY_lbl" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo44 \
        -font {-family {Segoe UI} -size 12} -textvariable combobox \
        -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$top.tCo44" "SY_box" vTcl:WidgetProc "Toplevel1" 1
    button $top.but50 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 12} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -relief ridge -text Activate 
    vTcl:DefineAlias "$top.but50" "activate_btn" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but43 \
        -in $top -x 10 -y 10 -width 157 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but44 \
        -in $top -x 180 -y 10 -width 157 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.but45 \
        -in $top -x 350 -y 10 -width 157 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.but46 \
        -in $top -x 520 -y 10 -width 157 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.but47 \
        -in $top -x 690 -y 10 -width 157 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.but48 \
        -in $top -x 860 -y 10 -width 157 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.but49 \
        -in $top -x 1030 -y 10 -width 157 -height 44 -anchor nw \
        -bordermode ignore 
    place $top.tSe50 \
        -in $top -x 0 -y 70 -width 1210 -anchor nw -bordermode inside 
    place $top.lab52 \
        -in $top -x 10 -y 100 -width 74 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo54 \
        -in $top -x 80 -y 100 -width 143 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 250 -y 100 -width 74 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.tCo56 \
        -in $top -x 330 -y 100 -width 143 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.but57 \
        -in $top -x 520 -y 100 -width 117 -relwidth 0 -height 34 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.014 -y 150 -width 104 -relwidth 0 -height 41 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.scr59 \
        -in $top -x 10 -y 200 -width 1180 -relwidth 0 -height 437 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 720 -y 100 -width 164 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tCo44 \
        -in $top -x 900 -y 100 -width 143 -height 31 -anchor nw \
        -bordermode ignore 
    place $top.but50 \
        -in $top -x 1070 -y 100 -width 117 -height 34 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

