#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#    Jan 17, 2020 12:48:17 PM CST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import AddSubject_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = SubjectsGUI(root)
    AddSubject_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = SubjectsGUI(w)
    AddSubject_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class SubjectsGUI:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        window_width = 1207
        window_height = 536
        screen_width = top.winfo_screenwidth()
        screen_height = top.winfo_screenheight()
        x_coordinate = int((screen_width / 2) - (window_width / 2))
        y_coordinate = int((screen_height / 2) - (window_height / 2))
        top.geometry("{}x{}+{}+{}".format(window_width, window_height, x_coordinate, y_coordinate))
        top.resizable(False, False)
        top.title("Scheduling System")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.back_btn = tk.Button(top)
        self.back_btn.place(relx=0.008, rely=0.019, height=44, width=157)
        self.back_btn.configure(activebackground="#ffffff")
        self.back_btn.configure(activeforeground="#000000")
        self.back_btn.configure(background="#ffffff")
        self.back_btn.configure(disabledforeground="#a3a3a3")
        self.back_btn.configure(font="-family {Segoe UI} -size 12")
        self.back_btn.configure(foreground="#000000")
        self.back_btn.configure(highlightbackground="#d9d9d9")
        self.back_btn.configure(highlightcolor="black")
        self.back_btn.configure(pady="0")
        self.back_btn.configure(relief="ridge")
        self.back_btn.configure(text='''Back''')

        self.TSeparator1 = ttk.Separator(top)
        self.TSeparator1.place(relx=0.0, rely=0.131, relwidth=1.002)

        self.grade_lbl = tk.Label(top)
        self.grade_lbl.place(relx=0.008, rely=0.168, height=41, width=64)
        self.grade_lbl.configure(activebackground="#f9f9f9")
        self.grade_lbl.configure(activeforeground="black")
        self.grade_lbl.configure(background="#d9d9d9")
        self.grade_lbl.configure(disabledforeground="#a3a3a3")
        self.grade_lbl.configure(font="-family {Segoe UI} -size 14")
        self.grade_lbl.configure(foreground="#000000")
        self.grade_lbl.configure(highlightbackground="#d9d9d9")
        self.grade_lbl.configure(highlightcolor="black")
        self.grade_lbl.configure(text='''Grade:''')

        self.grade_var = tk.StringVar()
        self.grade_entry = tk.Entry(top)
        self.grade_entry.place(relx=0.075, rely=0.168, height=40, relwidth=0.136)
        self.grade_entry.configure(background="white")
        self.grade_entry.configure(disabledforeground="#a3a3a3")
        self.grade_entry.configure(font="-family {Segoe UI} -size 12")
        self.grade_entry.configure(foreground="#000000")
        self.grade_entry.configure(highlightbackground="#d9d9d9")
        self.grade_entry.configure(highlightcolor="black")
        self.grade_entry.configure(insertbackground="black")
        self.grade_entry.configure(selectbackground="#c4c4c4")
        self.grade_entry.configure(selectforeground="black")
        self.grade_entry.configure(textvariable=self.grade_var)

        self.subject_lbl = tk.Label(top)
        self.subject_lbl.place(relx=0.008, rely=0.28, height=41, width=64)
        self.subject_lbl.configure(activebackground="#f9f9f9")
        self.subject_lbl.configure(activeforeground="black")
        self.subject_lbl.configure(background="#d9d9d9")
        self.subject_lbl.configure(disabledforeground="#a3a3a3")
        self.subject_lbl.configure(font="-family {Segoe UI} -size 14")
        self.subject_lbl.configure(foreground="#000000")
        self.subject_lbl.configure(highlightbackground="#d9d9d9")
        self.subject_lbl.configure(highlightcolor="black")
        self.subject_lbl.configure(text='''Subject:''')

        self.subject_var = tk.StringVar()
        self.subject_entry = tk.Entry(top)
        self.subject_entry.place(relx=0.075, rely=0.28, height=40
                , relwidth=0.136)
        self.subject_entry.configure(background="white")
        self.subject_entry.configure(disabledforeground="#a3a3a3")
        self.subject_entry.configure(font="-family {Segoe UI} -size 12")
        self.subject_entry.configure(foreground="#000000")
        self.subject_entry.configure(highlightbackground="#d9d9d9")
        self.subject_entry.configure(highlightcolor="black")
        self.subject_entry.configure(insertbackground="black")
        self.subject_entry.configure(selectbackground="#c4c4c4")
        self.subject_entry.configure(selectforeground="black")
        self.subject_entry.configure(textvariable=self.subject_var)

        self.duration_lbl = tk.Label(top)
        self.duration_lbl.place(relx=0.215, rely=0.28, height=41, width=84)
        self.duration_lbl.configure(activebackground="#f9f9f9")
        self.duration_lbl.configure(activeforeground="black")
        self.duration_lbl.configure(background="#d9d9d9")
        self.duration_lbl.configure(disabledforeground="#a3a3a3")
        self.duration_lbl.configure(font="-family {Segoe UI} -size 14")
        self.duration_lbl.configure(foreground="#000000")
        self.duration_lbl.configure(highlightbackground="#d9d9d9")
        self.duration_lbl.configure(highlightcolor="black")
        self.duration_lbl.configure(text='''Duration:''')

        self.duration_var = tk.StringVar()
        self.duration_entry = tk.Entry(top)
        self.duration_entry.place(relx=0.29, rely=0.28, height=40
                , relwidth=0.136)
        self.duration_entry.configure(background="white")
        self.duration_entry.configure(disabledforeground="#a3a3a3")
        self.duration_entry.configure(font="-family {Segoe UI} -size 12")
        self.duration_entry.configure(foreground="#000000")
        self.duration_entry.configure(highlightbackground="#d9d9d9")
        self.duration_entry.configure(highlightcolor="black")
        self.duration_entry.configure(insertbackground="black")
        self.duration_entry.configure(selectbackground="#c4c4c4")
        self.duration_entry.configure(selectforeground="black")
        self.duration_entry.configure(textvariable=self.duration_var)

        self.addSubject_btn = tk.Button(top)
        self.addSubject_btn.place(relx=0.431, rely=0.289, height=34, width=67)
        self.addSubject_btn.configure(activebackground="#ffffff")
        self.addSubject_btn.configure(activeforeground="#000000")
        self.addSubject_btn.configure(background="#ffffff")
        self.addSubject_btn.configure(disabledforeground="#a3a3a3")
        self.addSubject_btn.configure(foreground="#000000")
        self.addSubject_btn.configure(highlightbackground="#d9d9d9")
        self.addSubject_btn.configure(highlightcolor="black")
        self.addSubject_btn.configure(pady="0")
        self.addSubject_btn.configure(relief="ridge")
        self.addSubject_btn.configure(text='''Add''')

        self.style.configure('Treeview.Heading',  font="TkDefaultFont")
        self.subject_treeview = ScrolledTreeView(top, columns=("subject", "duration"), show="headings")
        self.subject_treeview.place(relx=0.075, rely=0.392, relheight=0.461
                , relwidth=0.365)
        self.subject_treeview.heading(0, text="Subject")
        self.subject_treeview.heading(1, text="Duration")
        self.subject_treeview.column(0, anchor="center")
        self.subject_treeview.column(1, anchor="center")

        self.submit_btn = tk.Button(top)
        self.submit_btn.place(relx=0.075, rely=0.877, height=54, width=187)
        self.submit_btn.configure(activebackground="#1aff12")
        self.submit_btn.configure(activeforeground="#000000")
        self.submit_btn.configure(background="#1aff12")
        self.submit_btn.configure(disabledforeground="#a3a3a3")
        self.submit_btn.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.submit_btn.configure(foreground="#ffffff")
        self.submit_btn.configure(highlightbackground="#d9d9d9")
        self.submit_btn.configure(highlightcolor="black")
        self.submit_btn.configure(pady="0")
        self.submit_btn.configure(relief="ridge")
        self.submit_btn.configure(text='''SUBMIT''')

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledTreeView(AutoScroll, ttk.Treeview):
    '''A standard ttk Treeview widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        ttk.Treeview.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





